name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs_on: ubuntu-latest
    steps:
      -  name: Print hello
         run: echo "Ciao gente!"
      -  name: Print goodbye
         run: echo "Addio gente!"
